baseURL: "https://543t.netlify.app/"
languageCode: "en-us"
title: "543T"
theme: "PaperMod"

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  cover:
    responsive: true
  env: production  # å¾ˆé‡è¦ï¼æœƒå•Ÿç”¨å®Œæ•´ meta tag
  title: "543T"
  images:
    - "/images/home.webp"

  description: "3T çš„æŠ€è¡“èˆ‡ç”Ÿæ´»ç´€éŒ„éƒ¨è½æ ¼"
  defaultTheme: dark

  homeInfoParams:
    Title: "Hi, æˆ‘æ˜¯ 3T ğŸ‘‹"
    Content: "é€™è£¡æ˜¯æˆ‘çš„æŠ€è¡“èˆ‡ç”Ÿæ´»ç´€éŒ„"

  author: Me
  ShowReadingTime: true
  ShowWordCount: true
  ShowShareButtons: true
  responsiveImages: true
  ShowToc: true          # åœ¨å³å´é¡¯ç¤º TOC
  TocOpen: true          # é è¨­å±•é–‹ç›®éŒ„ï¼ˆå¯æ”¹ç‚º falseï¼‰
  Comments: true

  mainSections: []

  profileMode:
    enabled: true
    title: "Hi, æˆ‘æ˜¯ 3T ğŸ‘‹" # optional default will be site title
    subtitle: |
      ğŸ’» æŠ€è¡“ç­†è¨˜èˆ‡å¯¦ä½œ  
      ğŸ“¦ å°ˆæ¡ˆé–‹ç™¼èˆ‡å¾Œç«¯æ¶æ§‹  
      ğŸš€ æ±‚è·æ”»ç•¥èˆ‡ç³»çµ±åˆ†æå¿ƒå¾—  
      âœï¸ åˆ†äº«ç”Ÿæ´»è§€å¯Ÿèˆ‡å­¸ç¿’æ­·ç¨‹
    imageUrl: "/images/3t.webp" # optional
    imageTitle: "3T çš„é ­åƒ" # optional
    imageWidth: 200 # custom size
    imageHeight: 200 # custom size

  socialIcons:
    - name: github
      url: "https://github.com/yu-sooong"
    - name: email
      url: "mailto:ssocde543@gmail.com"

  assets:
    css:
      - "css/extra.css"
menu:
  main:
    - identifier: blog
      name: "blog"
      url: /posts/
      weight: 1
    - identifier: about
      name: "about"
      url: /about/
      weight: 2
    - identifier: tags
      name: "tags"
      url: /tags/
      weight: 3
    - identifier: resume
      name: "resume"
      url: https://www.cake.me/tinnyu
      weight: 4
